version: '3.8'

services:
  server-demo:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017/mydatabase # Replace mydatabase with your MongoDB database name

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
